import { type AppRoute } from "@abeyjs/view";

/** 
 * PLACEHOLDER - This file is automatically generated by abey-generate-routes.
 * It will be overwritten on the first run of the dev server or build.
 */
export function getRoutes(): AppRoute[] {
  return [];
}
