/**
 * Agent, flow, intent, and channel event names for the Dataaaa ecosystem.
 * Generated by `abeyjs generate ecosystem`.
 */
export const DataaaaEcosystem = {
  agentId: "ecosystem:dataaaa:agent",
  flowId: "ecosystem:dataaaa:flow",
  intentTick: "Dataaaa/Tick",
  intentLoadTable: "Dataaaa/TableLoad",
  intentTableSelection: "Dataaaa/TableSelection",
  intentTableAction: "Dataaaa/TableAction",
  eventTicked: "omega/ecosystem/dataaaa/ticked",
  eventTableColumns: "omega/ecosystem/dataaaa/tableColumns",
  eventTableActions: "omega/ecosystem/dataaaa/tableActions",
  eventTableItems: "omega/ecosystem/dataaaa/tableItems",
} as const;
