#!/usr/bin/env node
/** AbeyJs CLI — project scaffolding, OpenAPI wiring, view/ecosystem generators. */
import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { isAbsolute, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import openapiTS, { astToString, COMMENT_HEADER, type OpenAPITSOptions } from "openapi-typescript";
import { addOpenapiToApp } from "./openapi-add-wires.js";
import { runConnect } from "./openapi-connect.js";
import { listCrudCandidates, runGenerateViewsWithOptions, type ScaffoldMode } from "./openapi-generate-views.js";
import {
  buildEcosystemWireInstructions,
  runGenerateEcosystem,
} from "./generate-ecosystem.js";

const usage = `abeyjs — AbeyJs helper CLI

  abeyjs new <folder> [--template admin|abeyjs|empty|minimal] [--shell dashboard|appbar]
  abeyjs create <folder> [options]   (alias)
  abeyjs init <folder> [options]     (same as \`new\`: copy template in one step)
      Scaffolds Vite+TS+AbeyJs. Templates \`abeyjs\` / \`empty\` (same starter; disk: \`templates/empty\`) and \`admin\` ship a runnable app;
      \`minimal\` is a tiny workspace skeleton with only @abeyjs/core.
      \`--shell\` applies only to \`--template admin\`: \`dashboard\` = top bar + side nav + <main> (default);
      \`appbar\` = compact app bar + sidebar.
      Does not run npm install.
  abeyjs add openapi <folder> [--proxy <https://host:port>] [--openapi-path <path relative to proxy>]
      In an existing Vite+AbeyJs project: adds @abeyjs/openapi, @abeyjs/http, patches vite (proxies /api + /swagger),
      .env.example, omegaSetup helpers (initOpenApi + getOpenApi), CRUD route + view (mountOpenApiCrudView).
      Then: copy .env and npm i.
      Defaults: --proxy https://127.0.0.1:7019 and --openapi-path /swagger/v1/swagger.json
  abeyjs connect <swagger-url> [--target <folder>]
      Detects CRUD-ish entities from OpenAPI and writes .abeyjs/connect.json.
      Also writes abeyjs.connect.yml for widget/combo tuning.
      Use --insecure to trust self-signed HTTPS certs (dev only).
  abeyjs generate views [--target <folder>] [--scaffold minimal|full] [--full-scaffold]
      Generates CRUD views per entity (ts/html/css) and registers routes/sidebar.
      Requires a prior \`abeyjs connect\`.
      Default layout: \`src/routes.ts\`, \`src/views\`, \`src/flows\`, \`src/services/http.ts\`.
      \`--scaffold full\` (or \`--full-scaffold\`) adds extra layers (\`src/app\`, \`src/ui\`, \`src/infra\`, use-cases).
  abeyjs generate ecosystem <Name> [--feature-root <path>] [--target <folder>]
  abeyjs g ecosystem <Name> [--feature-root <path>] [--target <folder>]   (alias)
      Creates \`ui/\` (html, css, ts) and \`omega/\` (semantics, behavior, agent, flow, register) under the feature path.
      Without \`--feature-root\`, drops a \`./<kebab-name>/\` folder relative to \`--target\`.
      Best-effort patches \`src/omegaSetup.ts\` and \`src/routes.ts\` when present.
  abeyjs codegen <openapi.json|yaml> -o, --out <dir>
      Generate api-types.ts and omegaSetup.generated.ts stub.
  abeyjs help
      Show this text
`;

type Spec = { paths?: Record<string, unknown>; openapi?: string; swagger?: string; info?: { title?: string } };

function generateStub(spec: Spec, partialYamlNote: boolean): string {
  const pathKeys = spec.paths ? Object.keys(spec.paths).slice(0, 24) : [];
  const list = pathKeys.length
    ? pathKeys.map((k) => `  //   ${k}`).join("\n")
    : "  //   (no path list — " + (partialYamlNote ? "YAML: wire paths in omegaSetup.ts" : "empty spec") + ")";
  const version = spec.openapi ?? spec.swagger;
  return `/**
 * AUTO-GENERATED by \`abeyjs codegen\` — import from your omegaSetup.ts
 */
import { createOmegaRuntime, type OmegaRuntime } from '@abeyjs/runtime';

/** Central registration stub — extend with intents, HTTP, and agents in omegaSetup.ts. */
export function omegaSetupGenerated(): OmegaRuntime {
  const runtime = createOmegaRuntime();
  // ${spec.info?.title ? `API: ${spec.info.title}` : "API: (name from OpenAPI not loaded)"} ${version ? ` — ${version}` : ""}
  // OpenAPI path hints (register intents and HTTP in your app):
${list}
  // runtime.onIntent("Resource/List", (payload, ctx) => { ... });
  return runtime;
}
`;
}

type InitTemplate = "admin" | "abeyjs" | "minimal";
type InitShell = "dashboard" | "appbar";

function toWorkspaceSafePackageName(raw: string): string {
  const base = raw.trim().toLowerCase();
  const cleaned = base
    .replace(/[/\\]+/g, "-")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+/, "")
    .replace(/-+$/, "");
  // npm package name constraints are stricter, but this is "good enough" for workspace uniqueness.
  return cleaned.length > 0 ? cleaned : "abeyjs-app";
}

async function patchPackageJsonName(targetDir: string, nameHint: string): Promise<void> {
  const pkgPath = join(targetDir, "package.json");
  try {
    const raw = await readFile(pkgPath, "utf-8");
    const pkg = JSON.parse(raw) as Record<string, unknown>;
    pkg.name = toWorkspaceSafePackageName(nameHint);
    await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf-8");
  } catch {
    // If parsing fails or file missing, do nothing.
  }
}

type ParseResult =
  | { kind: "help" }
  | { kind: "codegen"; openapi: string; out: string }
  | { kind: "init"; target?: string; template: InitTemplate; shell: InitShell }
  | { kind: "addOpenapi"; target: string; proxy: string; openApiPath: string }
  | { kind: "connect"; swaggerUrl: string; target: string; insecure: boolean }
  | { kind: "generateViews"; target: string; scaffold: ScaffoldMode }
  | { kind: "generateEcosystem"; name: string; featureRoot?: string; target: string }
  | { kind: "err" };

function parseInitTemplate(a: string[]): { template: InitTemplate; shell: InitShell; rest: string[]; target?: string } {
  const rest: string[] = [];
  let template: InitTemplate = "abeyjs";
  let shell: InitShell = "dashboard";
  let target: string | undefined;
  for (let i = 0; i < a.length; i += 1) {
    if (a[i] === "--template" && a[i + 1]) {
      const t = a[i + 1]! as string;
      if (t === "admin" || t === "abeyjs" || t === "minimal" || t === "empty") {
        template = t === "empty" ? "abeyjs" : t;
        i += 1;
        continue;
      }
    }
    if (a[i] === "--shell" && a[i + 1]) {
      const s = a[i + 1]! as string;
      if (s === "dashboard" || s === "appbar") {
        shell = s;
        i += 1;
        continue;
      }
    }
    if (a[i] === "--target" && a[i + 1]) {
      target = a[i + 1]!;
      i += 1;
      continue;
    }
    if (a[i]?.startsWith("--target=")) {
      target = a[i]!.slice("--target=".length);
      continue;
    }
    rest.push(a[i]!);
  }
  return { template, shell, rest, target };
}

function parseArgs(argv: string[]): ParseResult {
  const a = argv.slice(2);
  if (a.length === 0 || a[0] === "help" || a[0] === "--help" || a[0] === "-h") {
    return { kind: "help" };
  }
  if (a[0] === "init" || a[0] === "new" || a[0] === "create") {
    const { rest, template, shell, target } = parseInitTemplate(a.slice(1));
    const fromArg = target ?? rest[0];
    const fromNpmConfig = process.env.npm_config_target;
    return { kind: "init", target: fromArg ?? fromNpmConfig, template, shell };
  }
  if (a[0] === "add" && a[1] === "openapi") {
    const fromPositional = a[2] && !a[2].startsWith("--") ? a[2] : undefined;
    const target = fromPositional ?? process.env.npm_config_target ?? ".";
    let proxy = process.env.npm_config_proxy ?? "https://127.0.0.1:7019";
    let openApiPath = process.env.npm_config_openapi_path ?? "/swagger/v1/swagger.json";
    for (let k = fromPositional ? 3 : 2; k < a.length; k += 1) {
      if (a[k] === "--proxy" && a[k + 1]) {
        proxy = a[k + 1]!;
        k += 1;
        continue;
      }
      if (a[k] === "--openapi-path" && a[k + 1]) {
        openApiPath = a[k + 1]!;
        k += 1;
        continue;
      }
    }
    return { kind: "addOpenapi", target, proxy, openApiPath: normalizeOpenApiPath(openApiPath) };
  }
  if (a[0] === "codegen") {
    const openapi = a[1]!;
    const oIdx = a.indexOf("-o");
    const outIdx = a.indexOf("--out");
    const i = oIdx >= 0 ? oIdx : outIdx;
    if (openapi && i >= 0 && a[i + 1]) {
      return { kind: "codegen", openapi, out: a[i + 1]! };
    }
    return { kind: "err" };
  }
  if (a[0] === "connect") {
    let target = process.env.npm_config_target ?? ".";
    let insecure = false;
    let swaggerUrl: string | undefined;
    for (let i = 1; i < a.length; i += 1) {
      const arg = a[i]!;
      if (!arg.startsWith("--") && swaggerUrl == null) {
        swaggerUrl = arg;
        continue;
      }
      if (a[i] === "--target" && a[i + 1]) {
        target = a[i + 1]!;
        i += 1;
        continue;
      }
      if (a[i]?.startsWith("--target=")) {
        target = a[i]!.slice("--target=".length);
        continue;
      }
      if (a[i] === "--insecure") {
        insecure = true;
        continue;
      }
    }
    if (swaggerUrl) {
      return { kind: "connect", swaggerUrl, target, insecure };
    }
    return { kind: "err" };
  }
  if (
    (a[0] === "generate" && a[1] === "ecosystem") ||
    (a[0] === "g" && a[1] === "ecosystem")
  ) {
    const tokens = a.slice(2);
    let target = process.env.npm_config_target ?? ".";
    let featureRoot: string | undefined;
    let name: string | undefined;
    for (let i = 0; i < tokens.length; i += 1) {
      const t = tokens[i]!;
      if (t === "--target" && tokens[i + 1]) {
        target = tokens[i + 1]!;
        i += 1;
        continue;
      }
      if (t.startsWith("--target=")) {
        target = t.slice("--target=".length);
        continue;
      }
      if (t === "--feature-root" && tokens[i + 1]) {
        featureRoot = tokens[i + 1]!;
        i += 1;
        continue;
      }
      if (t.startsWith("--feature-root=")) {
        featureRoot = t.slice("--feature-root=".length);
        continue;
      }
      if (!t.startsWith("--") && name == null) {
        name = t;
      }
    }
    if (name) {
      return { kind: "generateEcosystem", name, featureRoot, target };
    }
    return { kind: "err" };
  }
  if (a[0] === "generate" && a[1] === "views") {
    let target = process.env.npm_config_target ?? ".";
    let scaffold: ScaffoldMode = "minimal";
    for (let i = 2; i < a.length; i += 1) {
      if (a[i] === "--target" && a[i + 1]) {
        target = a[i + 1]!;
        i += 1;
        continue;
      }
      if (a[i]?.startsWith("--target=")) {
        target = a[i]!.slice("--target=".length);
        continue;
      }
      if (a[i] === "--full-scaffold") {
        scaffold = "full";
        continue;
      }
      if (a[i] === "--scaffold" && a[i + 1]) {
        const s = a[i + 1]!;
        if (s === "minimal" || s === "full") {
          scaffold = s;
        }
        i += 1;
        continue;
      }
      if (a[i]?.startsWith("--scaffold=")) {
        const s = a[i]!.slice("--scaffold=".length);
        if (s === "minimal" || s === "full") {
          scaffold = s;
        }
        continue;
      }
    }
    return { kind: "generateViews", target, scaffold };
  }
  return { kind: "help" };
}

const opts: OpenAPITSOptions = { exportType: true };

function resolveFromInvocationDir(inputPath: string): string {
  if (isAbsolute(inputPath)) {
    return inputPath;
  }
  const invokedFrom = process.env.INIT_CWD?.trim();
  return resolve(invokedFrom && invokedFrom.length > 0 ? invokedFrom : process.cwd(), inputPath);
}

function normalizeOpenApiPath(rawPath: string): string {
  const p = rawPath.trim();
  if (p.startsWith("/")) {
    return p;
  }
  const swaggerIdx = p.toLowerCase().indexOf("/swagger/");
  if (swaggerIdx >= 0) {
    return p.slice(swaggerIdx);
  }
  return p;
}

async function askProjectName(): Promise<string> {
  if (!input.isTTY || !output.isTTY) {
    throw new Error("Missing project name. Non-interactive mode: abeyjs init <folder> (e.g. abeyjs init my-app).");
  }
  const rl = createInterface({ input, output });
  try {
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const ans = (await rl.question("Project name: ")).trim();
      if (ans.length > 0) {
        return ans;
      }
    }
  } finally {
    rl.close();
  }
}

async function askGenerateEntities(candidates: string[]): Promise<string[] | null> {
  if (!input.isTTY || !output.isTTY) {
    return null;
  }
  const rl = createInterface({ input, output });
  try {
    // eslint-disable-next-line no-console
    console.log("CRUD entity candidates:");
    for (const name of candidates) {
      // eslint-disable-next-line no-console
      console.log(`- ${name}`);
    }
    const mode = (
      await rl.question("Generate all views now? [Y/n] ")
    )
      .trim()
      .toLowerCase();
    if (mode === "" || mode === "y" || mode === "yes" || mode === "s" || mode === "si") {
      return null;
    }
    const picked: string[] = [];
    for (const name of candidates) {
      const ans = (
        await rl.question(`Generate view for ${name}? [y/N] `)
      )
        .trim()
        .toLowerCase();
      if (ans === "y" || ans === "yes" || ans === "s" || ans === "si") {
        picked.push(name);
      }
    }
    return picked;
  } finally {
    rl.close();
  }
}

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
async function run() {
  const p = parseArgs(process.argv);
  if (p.kind === "err") {
    const argv = process.argv.slice(2);
    if (
      (argv[0] === "generate" && argv[1] === "ecosystem") ||
      (argv[0] === "g" && argv[1] === "ecosystem")
    ) {
      // eslint-disable-next-line no-console
      console.error(
        "Usage: abeyjs generate ecosystem <Name> [--feature-root <path>] [--target <folder>]\n" +
          "Example (cwd): abeyjs generate ecosystem Auth\n" +
          "Example (paths): abeyjs generate ecosystem Auth --feature-root src/auth --target .",
      );
      process.exit(1);
    }
    // eslint-disable-next-line no-console
    console.error(usage);
    process.exit(1);
  }
  if (p.kind === "help") {
    // eslint-disable-next-line no-console
    console.log(usage);
    return;
  }
  if (p.kind === "addOpenapi") {
    const targetDir = resolveFromInvocationDir(p.target);
    await addOpenapiToApp(targetDir, { proxyTarget: p.proxy, openApiPath: p.openApiPath });
    const envExample = join(targetDir, ".env.example");
    const env = join(targetDir, ".env");
    try {
      await cp(envExample, env, { force: false });
    } catch {
      // Skip if .env already exists.
    }
    // eslint-disable-next-line no-console
    console.log("OpenAPI/CRUD wiring applied. Next: `npm i` and tune `.env` / proxy if needed.");
    // eslint-disable-next-line no-console
    console.log(`Path: ${targetDir}`);
    return;
  }
  if (p.kind === "connect") {
    const targetDir = resolveFromInvocationDir(p.target);
    const r = await runConnect(targetDir, p.swaggerUrl, { insecure: p.insecure });
    const byType = {
      crud: r.contract.entities.filter((e) => e.type === "crud").map((e) => e.name),
      action: r.contract.entities.filter((e) => e.type === "action").map((e) => e.name),
      service: r.contract.entities.filter((e) => e.type === "service").map((e) => e.name),
    };
    // eslint-disable-next-line no-console
    console.log(`Connect OK. CRUD: ${byType.crud.join(", ") || "(none)"}`);
    // eslint-disable-next-line no-console
    console.log(`Actions: ${byType.action.join(", ") || "(none)"} · Services: ${byType.service.join(", ") || "(none)"}`);
    // eslint-disable-next-line no-console
    console.log(`Contract: ${r.contractPath}`);
    // eslint-disable-next-line no-console
    console.log(`Config: ${r.yamlPath}`);
    return;
  }
  if (p.kind === "generateEcosystem") {
    const targetDir = resolveFromInvocationDir(p.target);
    // npm scripts run with cwd at package root; INIT_CWD preserves where the user invoked it.
    const invocationDir = resolve(process.env.INIT_CWD?.trim() || process.cwd());
    const r = await runGenerateEcosystem({
      projectRoot: targetDir,
      featureRoot: p.featureRoot,
      rawName: p.name,
      invocationDir,
    });
    for (const line of buildEcosystemWireInstructions(targetDir, r)) {
      // eslint-disable-next-line no-console
      console.log(line);
    }
    return;
  }
  if (p.kind === "generateViews") {
    const targetDir = resolveFromInvocationDir(p.target);
    const candidates = await listCrudCandidates(targetDir);
    if (candidates.length === 0) {
      throw new Error("No CRUD entity candidates found. Run `abeyjs connect` first.");
    }
    const chosen = await askGenerateEntities(candidates);
    if (chosen && chosen.length === 0) {
      throw new Error("No entities selected for generation.");
    }
    const r =
      chosen === null
        ? await runGenerateViewsWithOptions(targetDir, { scaffold: p.scaffold })
        : await runGenerateViewsWithOptions(targetDir, { onlyEntities: chosen, scaffold: p.scaffold });
    // eslint-disable-next-line no-console
    console.log(`Views generated: ${r.generatedEntities.join(", ")}`);
    // eslint-disable-next-line no-console
    console.log(`Path: ${targetDir}`);
    return;
  }
  if (p.kind === "init") {
    const target = p.target && p.target.trim() !== "" ? p.target.trim() : await askProjectName();
    const dir = resolveFromInvocationDir(target);
    await mkdir(dir, { recursive: true });
    const packageRoot = fileURLToPath(new URL("..", import.meta.url));
    const templateFolder = p.template === "abeyjs" ? "empty" : p.template;
    const from = join(packageRoot, "templates", templateFolder);
    if (templateFolder === "admin" || templateFolder === "empty") {
      await cp(from, dir, { recursive: true, force: true });
      // Ensure unique workspace package name (avoid collisions like "abeyjs-starter").
      await patchPackageJsonName(dir, target);
      if (p.template === "admin" && p.shell === "appbar") {
        const mainPath = join(dir, "src", "main.ts");
        const before = await readFile(mainPath, "utf-8");
        if (before.includes("dashboardLayout: true")) {
          await writeFile(
            mainPath,
            before.replace("dashboardLayout: true", "dashboardLayout: false"),
            "utf-8",
          );
        }
      }
      const shellLine =
        p.template === "admin" && p.shell === "appbar"
          ? " [shell appbar: compact app bar + sidebar]"
          : p.template === "admin"
            ? " [shell dashboard: top bar + sidebar + main content]"
            : "";
      const readMeLine3 =
        p.template === "admin"
          ? "3. Routes: src/routes.ts · home: src/home/home.ts (+ home.html/home.css) · intents/runtime: src/omegaSetup.ts · flows: src/flows · HTTP: src/services/http.ts (optional: --shell appbar)"
          : "3. Routes: src/routes.ts · home: src/views/home/ (app.home.view.html / .ts / .css) · intents/runtime: src/omegaSetup.ts · environments: src/environment.ts · assets: public/";
      await writeFile(
        join(dir, "README.txt"),
        [
          "Generated app (blank starter or admin shell).",
          `1. cd "${dir}" y npm i`,
          "2. npm run dev",
          readMeLine3,
          "4. Baseline: `src/flows/*` (helpers + intent/channel glue) + `src/services/http.ts` + `runtime.onIntent(...)` / `runtime.channel` in `src/omegaSetup.ts`.",
          "5. After `abeyjs connect`, run `abeyjs generate views` (default `--scaffold minimal`). Extra layers: `--scaffold full`.",
        ].join("\n"),
        "utf-8",
      );
      // eslint-disable-next-line no-console
      console.log(
        `Project created with template "${p.template}"` +
          (shellLine ? ` ${shellLine}` : ``) +
          ".",
      );
      // eslint-disable-next-line no-console
      console.log(`Path: ${dir}`);
      return;
    }
    const pkg = {
      name: toWorkspaceSafePackageName(target),
      private: true,
      type: "module",
      scripts: {
        codegen: "abeyjs codegen ./openapi.json -o ./src/generated",
      },
      dependencies: { "@abeyjs/core": "^0.1.0" },
    };
    await writeFile(join(dir, "package.json"), JSON.stringify(pkg, null, 2), "utf-8");
    await writeFile(
      join(dir, "README.txt"),
      [
        "1. npm i",
        "2. abeyjs codegen ./openapi.json -o ./src/generated",
        "3. Implement src/omegaSetup.ts (register agents + intents).",
        "4. Wire @abeyjs/view and @abeyjs/http in your bundler (Vite, etc.) or run: abeyjs init otherFolder --template admin",
      ].join("\n"),
      "utf-8",
    );
    const miniOpenapi = {
      openapi: "3.0.3",
      info: { title: "Starter", version: "0.0.0" },
      paths: { "/": { get: { responses: { "200": { description: "ok" } } } } } ,
    };
    await writeFile(join(dir, "openapi.json"), JSON.stringify(miniOpenapi, null, 2), "utf-8");
    await mkdir(join(dir, "src"), { recursive: true });
    await writeFile(
      join(dir, "src", "omegaSetup.example.ts"),
      `import { createOmegaRuntime } from "@abeyjs/runtime";

export function createOmega() {
  const runtime = createOmegaRuntime();
  // import { omegaSetupGenerated } from "./generated/omegaSetup.generated.js"
  // merge agents, intents, and HTTP integration here
  return { runtime };
}
`,
      "utf-8",
    );
    // eslint-disable-next-line no-console
    console.log("Created at: " + dir);
    return;
  }
  if (p.kind === "codegen") {
    const { openapi, out: outParam } = p;
    const outDir = resolveFromInvocationDir(outParam);
    const specPath = resolveFromInvocationDir(openapi);
    await mkdir(outDir, { recursive: true });
    const typesPath = join(outDir, "api-types.ts");
    const nodes = await openapiTS(pathToFileURL(specPath), opts);
    const out = COMMENT_HEADER + astToString(nodes, {});
    await writeFile(typesPath, out, "utf-8");

    let spec: Spec;
    let partialYaml = false;
    if (specPath.toLowerCase().endsWith(".json")) {
      spec = JSON.parse(await readFile(specPath, "utf-8")) as Spec;
    } else {
      const raw = await readFile(specPath, "utf-8");
      if (raw.trimStart().startsWith("{")) {
        try {
          spec = JSON.parse(raw) as Spec;
        } catch {
          spec = {};
          partialYaml = true;
        }
      } else {
        spec = {};
        partialYaml = true;
      }
    }

    const stubPath = join(outDir, "omegaSetup.generated.ts");
    await writeFile(stubPath, generateStub(spec, partialYaml), "utf-8");
    // eslint-disable-next-line no-console
    console.log("Wrote:\n  " + typesPath + "\n  " + stubPath);
  }
}

void run().catch((e) => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
